### ISSUE TITLE
missing answers

### ISSUE THREAD

**Issue by nembal** [Joshua-Stapleton/smartgpt-answers#1]
Love the data set, but as I started to look at some of the iterations, I found that many pdf-s just mention the location of the answer but the answer is missing. I looked around and many of the PDFs are missing the actual answers and it seems this is mostly a pre-run data set.

**Comment by Joshua-Stapleton** [comment]
Hi @nembal. Thanks for pointing this out, could you give examples of PDFs and specific question / answer numbers?

**Comment by nembal** [comment]
So, it seems that Abstract_algebra and Anatomy are the ones I expected for 3.5 and 4, but after those two categories, all other categories only have empty answer fields. 

What I mean as expected:
https://github.com/Joshua-Stapleton/smartgpt-answers/blob/main/SmartGPT_35_run/abstract_algebra.pdf
https://github.com/Joshua-Stapleton/smartgpt-answers/blob/main/SmartGPT_4_run/abstract_algebra.pdf

Everything else with missing answers: (random examples) 
https://github.com/Joshua-Stapleton/smartgpt-answers/blob/main/SmartGPT_35_run/college_medicine.pdf
https://github.com/Joshua-Stapleton/smartgpt-answers/blob/main/SmartGPT_35_run/high_school_government_and_politics.pdf
https://github.com/Joshua-Stapleton/smartgpt-answers/blob/main/SmartGPT_4_run/clinical_knowledge.pdf

**Comment by Joshua-Stapleton** [comment]
@nembal we explain in the video that we provide custom exemplars for a subset of 'problem-based' topics, which causes subjects (like abstract algebra and anatomy) to have longer, more verbose answers to questions. The answer fields are not 'empty' in other topics like clinical knowledge, they just contain the final answer (eg: "Final Answer: A"). If you look at all the examples you have provided, you will see that there are no missing answers, just shorter answers.

To give more concrete examples, due to the custom exemplars provided, abstract algebra will give answers like "We can simplify the expression $\sqrt{18}$ as $\sqrt{2 \cdot 9} = \sqrt{2 \cdot 3^2} = \sqrt{2} \cdot \sqrt{3...", whereas other topics like college medicine will give simple answers in the form "Final Answer: A". 

I hope that makes sense!

**Comment by nembal** [comment]
Ah. Yes, now that makes sense, I was just expecting to have the full answers as the first two documents and now I am seeing the correct final answers. Thanks for the heads up! ps: good work!!
